version: '3.8'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - "8000:8000"
    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "13306:3306"

    web:
        build:
            context: ./web
        ports:
            - "3000:3000"
